### ISSUE TITLE
Filter repositories by name or username

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/opensource#10]
Sometimes we want to find a specific repository or all the repositories of a user but the only way at this moment is walking through all pages until we find it but this is time-consuming and is not an easy way, so I suggest adding a search by repository name or username.

## Tasks

 - [x] Create a `Filter` component at `src/client/components/filter/Filter.js`
 - [x] The `Filter` component will have a text input (as shown in the image below).
 - [x] The `Filter` should follow the styles by http://materializecss.com
 - [x] The filter will be apply as soon as the user type.
 - [ ] Add the `Filter` into `src/client/components/repositories/popular/Popular.js` and `src/client/components/repositories/new/New.js` where it will filter both lists.
 - [ ] Repositories should be filtered by `name` or `description` fields. ~When the filter begins with @ then repositories should be filtered by `user.name` or `user.login`.~
 - [ ] ~Both `Popular.js` and `New.js` will have a note to indicate that a filter can be applied by owners using @ (as shown in the image below)~

![repositories](https://user-images.githubusercontent.com/439839/31837779-0ae54a56-b5a8-11e7-93a4-d02416220124.png)

**Comment by rmariuzzo** [comment]
@DannyFeliz I think this feature will be interesting to implement at some point, but it require details on how to get it done. I would like to wait until we get some other task ready and then revisit this. Meanwhile, can you add detailed instructions for a new contributor in the form of a task list?

**Comment by rmariuzzo** [comment]
I think now is the time to focus on add the search bar for repos and devs pages. 👌

**Comment by iCueto** [comment]
I'm working on this. 💯

**Comment by rmariuzzo** [comment]
@iCueto please, take in account the major refactor I did.

**Comment by rmariuzzo** [comment]
WIP

![screencast 2017-10-25 11-26-27](https://user-images.githubusercontent.com/439839/32008427-aa8bee12-b958-11e7-9f48-7e7af4e89b92.gif)
