### ISSUE TITLE
Create history for users

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#19]
We would like to track some changes for users when the scrape runs.

**Tasks:**
 - [x] Create a migration scripts using `yarn sequelize -- migration:create`.
 - [x] Define the table `users_history` to be similar to `users` except for the field `scrapedAt`.
 - [ ] During scraper execution detect any kind of change made. If a change was detected then create a record into `users_history` containing the now old version of the users, the `createdAt` field will be current date to keep the history time.

**Comment by rmariuzzo** [comment]
I will work on this now.
