### ISSUE TITLE
Create history for repos

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#20]
We would like to track some changes for repos when the scrape runs.

**Tasks:**
 - [x] Create a migration script using `yarn sequelize -- migration:create --name repo-changes`.
 - [x] Define the table `repo_changes` to be similar to `repos` except for the field `scrapedAt`.
 - [x] During scraper execution detect any kind of change made. If a change was detected then create a record into `repo_changes` containing the now old version of the repo, the `createdAt` field will be current date to keep the history time.
