### ISSUE TITLE
Create CLI script for scraper

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#21]
Currently we have 3 NPM scripts for scraping purposes. However no script files exists. We would like to create a script files that support the three current actions for the scraper:

 1. `scrape` – scrape everything.
 1. `scrape --only=users` – scrape users only.
 1. `scrape --only=repos` – scrape repos only.

**Tasks:**

 - [ ] Create a script file at: `src/server/scripts/scrape.js`.
 - [ ] Follow [this guide](https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e) to add the proper shebang directive and setup permissions only. Do not add a `bin` entry.
 - [ ] The script file should support the options `--only` and only one of two values are accepted: `users` or `repos`. When that CLI option is specified, then only the specified set will be scraped.
 - [ ] Replace the 3 current NPM scripts (`scrape`, `scrape:users` and `scrape:repos`) with one script: `scrape` which will execute our new cli script defined at: `src/server/scripts/scrape.js`.

**Comment by uLan08** [comment]
I am interested in this. I'll give it a try :muscle:

**Comment by uLan08** [comment]
Weird, the argument is not being parsed in if I supply `--only=user` but if it's only `only=user` then it does.

**Comment by rmariuzzo** [comment]
Hi @uLan08! Please, use `[minimist](https://github.com/substack/minimist)` to parse CLI args, it will set the base for other CLI scripts. And it will help you a lot. ;-)

**Comment by uLan08** [comment]
@rmariuzzo I am still not able to parse it correctly. It seems that if I pass the option in the script entry in package json like this `"scrape": "./src/server/scripts/scrape.js --only=user"` then it is parsed correctly but if I passed it in thru `yarn scrape --only=user` then it doesn't. Any thoughts on this?

**Comment by rmariuzzo** [comment]
That's normal @uLan08. When you do `yarn scrape --only=user` the `--only` option is passed to yarn and in effect swallowed. To tell yarn to keep passing CLI options you have to do: 

```
yarn scrape -- --only=user
```

The same applies to NPM scripts. ;)

**Comment by uLan08** [comment]
Ah I didn't know that. I can get a PR up within a few minutes.
