### ISSUE TITLE
Create CLI script for generator

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#22]
Currently we have a single NPM script for data generation purposes. However no script files exists. We would like to create a script files that replace the data generation process.

**Tasks:**

 - [x] Create a script file at: `src/server/scripts/generate-data.js`.
 - [x] Follow [this guide](https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e) to add the proper shebang directive and setup permissions only. Do not add a `bin` entry.
 - [x] The script file should support a `--only` option and only one of two values are accepted: `users` or `repos`. When that CLI option is specified, then only the specified set will be generated.
 - [x] Replace the current single NPM script (`generate`, `scrape:users` and `scrape:repos`) with one script: `generate-data` which will execute our new cli script defined at: `src/server/scripts/generate-data.js`.

**Comment by jouderianjr** [comment]
Hey, I can do this 💃

**Comment by rmariuzzo** [comment]
All yours mate! Take in account we are using Node 8+.
