### ISSUE TITLE
Filter developers by name

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#42]
## Requirements

 - May depend on #10 

## Tasks

 - [ ] Create or reuse the `Filter` component at `src/client/components/filter/Filter.js` (more details on creating at #10).
 - [ ] Developers should be filtered by `name` or `login` fields.
 - [ ] Add the `Filter` into `src/client/components/repositories/popular/Popular.js` and `src/client/components/repositories/recently-joined/RecentlyJoined.js` where it will filter both lists.

**Comment by iCueto** [comment]
I'm going to work on this feature. :)

**Comment by rmariuzzo** [comment]
Hey @iCueto, I have just done a major refactor. Pull your changes from `develop` before the cataclysm.
