### ISSUE TITLE
Add page title for each page components

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/opensource#49]
We currently have a few page component that needs to set a page title.

### Tasks:

 - [ ] Install https://github.com/gaearon/react-document-title (`yarn add react-document-title`)
 - [ ] Remove the `title` tag from `src/client/index.html`.
 - [ ] Wrap output of `src/client/components/repositories/popular/Popular.js` with `DocumentTitle` and set `title` to: `Popular Repositories – Dominican Open Source`.
 - [ ] Wrap output of `src/client/components/repositories/trending/Trending.js` with `DocumentTitle` and set `title` to: `Trending Repositories – Dominican Open Source`.
 - [ ] Wrap output of `src/client/components/repositories/new/New.js` with `DocumentTitle` and set `title` to: `New Repositories – Dominican Open Source`.
 - [ ] Wrap output of `src/client/components/developers/popular/Popular.js` with `DocumentTitle` and set `title` to: `Popular Developers – Dominican Open Source`.
 - [ ] Wrap output of `src/client/components/developers/recently-joined/RecentlyJoined.js` with `DocumentTitle` and set `title` to: `Recently Joined Developers – Dominican Open Source`.
 - [ ] Wrap output of `src/client/components/developers/about/About.js` with `DocumentTitle` and set `title` to: `About and Statistics – Dominican Open Source`.

**Comment by janakact** [comment]
I'll do this one :)

**Comment by rmariuzzo** [comment]
Thank you @janakact! I'm going off now, will check your PR later!
